<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php 
foreach($css_files as $file): ?>
	<link type="text/css" rel="stylesheet" href="<?php echo $file; ?>" />
<?php endforeach; ?>
<?php foreach($js_files as $file): ?>
	<script src="<?php echo $file; ?>"></script>
<?php endforeach; ?>
<style type='text/css'>
body
{
	font-family: Arial;
	font-size: 14px;
}
a {
    color: blue;
    text-decoration: none;
    font-size: 14px;
}
a:hover
{
	text-decoration: underline;
}
table.display thead th {
    padding-left: 2px;
    padding-right: 2px;
}
table.dataTable {
    font-size: 12px;
}
.dataTables_filter, .dataTables_length, .dataTables_info, .dataTables_paginate  { 
    display: none; //tfoot tr th, 
}
</style>
</head>
<body>  
    <div>
		<?php echo $output; ?>
    </div>
</body>
<script>
    /*$('table.groceryCrudTable').on('draw.dt', function () {
        $('.DTTT_button').click();
        $( "<h1>Generated by Adserver</h1>" ).insertBefore( $(".dataTablesContainer") );
    });*/
    $(function(){
      $('.DTTT_button').click();
      //$( "<h1>Generated by Adserver</h1>" ).insertBefore( $(".dataTablesContainer") );
    });
</script>
</html>
